from api.views.base import BaseViewSet
from api.views.admin import AdminViewSet
from api.views.login import LoginViewSet
from api.views.lunch import LunchViewSet
from api.views.profile import ProfileViewSet
from api.views.team import TeamViewSet
from api.views.user import UserViewSet
from api.views.date import DateViewSet
from api.views.photo import PhotoViewSet
from api.views.propose_leave import ProposeLeaveViewSet
from api.views.actions import ActionViewSet
