# Generated by Django 2.2.7 on 2019-12-06 09:27

import django.core.validators
import django.utils.timezone
from django.db import migrations, models

import api.models.photo
import api.models.profile


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('date', models.DateField(null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('content', models.CharField(default=None, max_length=255, null=True)),
                ('reason', models.CharField(default=None, max_length=255, null=True)),
                ('type', models.CharField(
                    choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Full day', 'Full day')],
                    default='Full day', max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lunch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lunchdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('date', models.DateField(default=django.utils.timezone.now, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('photo',
                 models.ImageField(blank=True, max_length=255, null=True, upload_to=api.models.photo.name_file)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProposeLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('start', models.DateField(null=True)),
                ('end', models.DateField(null=True)),
                ('lunch', models.CharField(default='No', max_length=255)),
                ('start_hour', models.CharField(max_length=255, null=True)),
                ('end_hour', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(default='Pending', max_length=255)),
                ('comments', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('team_name', models.CharField(max_length=255)),
                ('team_email', models.EmailField(max_length=255)),
                ('team_leader', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Demo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bankaccount',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='salary',
        ),
        migrations.AddField(
            model_name='profile',
            name='account_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bank',
            field=models.CharField(
                choices=[('No bank', 'No bank'), ('ABBANK', 'ABBANK'), ('ACB', 'ACB'), ('AGRIBANK', 'AGRIBANK'),
                         ('BACABANK', 'BACABANK'), ('BIDV', 'BIDV'), ('DONGABANK', 'DONGABANK'),
                         ('EXIMBANK', 'EXIMBANK'), ('HDBANK', 'HDBANK'), ('IVB', 'IVB'), ('JCB', 'JCB'),
                         ('MASTERCARD', 'MASTERCARD'), ('MBBANK', 'MBBANK'), ('MSBANK', 'MSBANK'),
                         ('NAMABANK', 'NAMABANK'), ('NCB', 'NCB'), ('OCB', 'OCB'), ('OJB', 'OJB'),
                         ('PVCOMBANK', 'PVCOMBANK'), ('SACOMBANK', 'SACOMBANK'), ('SAIGONBANK', 'SAIGONBANK'),
                         ('SCB', 'SCB'), ('SHB', 'SHB'), ('TECHCOMBANK', 'TECHCOMBANK'), ('TPBANK', 'TPBANK'),
                         ('UPI', 'UPI'), ('VIB', 'VIB'), ('VIETCAPITALBANK', 'VIETCAPITALBANK'),
                         ('VIETCOMBANK', 'VIETCOMBANK'), ('VIETINBANK', 'VIETINBANK'), ('VISA', 'VISA'),
                         ('VNMART', 'VNMART'), ('VNPAYQR', 'VNPAYQR'), ('VPBANK', 'VPBANK')], default='No bank',
                max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_day',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='identity_number',
            field=models.CharField(max_length=20, null=True, validators=[
                django.core.validators.RegexValidator(message='A valid integer is required.', regex='^\\d+$')]),
        ),
        migrations.AddField(
            model_name='profile',
            name='personal_email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='teams',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='join_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='lunch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='lunch_weekly',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=api.models.profile.name_file),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=11, null=True, validators=[
                django.core.validators.RegexValidator(message='A valid integer is required.', regex='^\\d+$'),
                django.core.validators.MinLengthValidator(9)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='proposeleave',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leave',
                                    to='api.Profile'),
        ),
        migrations.AddField(
            model_name='photo',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo',
                                    to='api.Profile'),
        ),
        migrations.AddField(
            model_name='lunch',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lunch_date',
                                    to='api.Lunchdate'),
        ),
        migrations.AddField(
            model_name='lunch',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lunch_profile',
                                    to='api.Profile'),
        ),
        migrations.AddField(
            model_name='date',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='date',
                                    to='api.Profile'),
        ),
    ]
