# Generated by Django 2.2.7 on 2019-12-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0002_auto_20191206_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunchdate',
            name='veggie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='veggie',
            field=models.BooleanField(default=False),
        ),
    ]
