# Generated by Django 2.2.7 on 2020-09-04 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_workday', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dateoff',
            old_name='request_off_id',
            new_name='request_off',
        ),
    ]
